spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/game_buddy
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
