spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/game_buddy
    username: postgres
    password: root
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
  flyway:
    baseline-on-migrate: true
    create-schemas: true
