spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/game_buddy
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
